name: Run Van Tracker

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GEOTAB_PASSWORD: ${{ secrets.GEOTAB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python dfna-van-tracker.py
